### ISSUE TITLE
Cannot compile on windows (missing vray.lib)

### ISSUE THREAD

**Issue by instinct-vfx** [ChaosGroup/vray-for-fabric#1]
So first of all as there is no LD_LIBRARY_PATH on windows one needs to do some hackery to the SCons file to make it find the libs. But then there is still vray.lib missing (at least from my appsdk releases).

The only vray.lib i have on my system is from some old maya install. So two things:
1. Where can i get a matching/proper vray.lib.
2. Once i have that i can create a merge request for windows compilation if still needed.

Cheers,
Thorsten

**Comment by vkoylazov** [comment]
Hi Thorsten,

You can get vray.lib from a recent V-Ray for 3ds Max or Maya installation; probably the closer it is to the App SDK build date, the better. If you still have issues, I'll try to get you the exact .lib that matches the App SDK build (which build is that by the way? The one on the nightly builds server?)

Best regards,

Vlado

**Comment by instinct-vfx** [comment]
Heya,

i am currently using Fabric 2.0 and appsdk from the nightlies (1.07.00-vray33501-20160304)

Using vray.lib from a current nightly max gets me to compile, but during linking i get a lot of unresolved external symbols.

Am i missing a path still or is this actually an issue with the lib from the max release?

Cheers and thanks,
Thorsten

**Comment by instinct-vfx** [comment]
Oh btw, i have by no means the need for these specific versions. I can use whatever works out of the box atm if that helps.

**Comment by vkoylazov** [comment]
Can you show me the errors? You might to link against other libs as well.

Best regards,

Vlado

**Comment by instinct-vfx** [comment]
Sure, here is a copy/paste: http://pastebin.com/raw/iuzgFJQB

**Comment by vkoylazov** [comment]
Hi Thorsten,

These come from the VRaySDKLibrary.lib, so you should link to that one too.

Best regards,

Vlado

**Comment by instinct-vfx** [comment]
Hm. They are in the same place and both are added in the env at the same time. So i am unsure why it does not pick that one up.

**Comment by vkoylazov** [comment]
Can you show me the command line used to invoke the linker?

Best regards,

Vlado

**Comment by instinct-vfx** [comment]
Sure. Needed a tiny bit of hackery, as the provided scons scripts hides them by default :P

link /nologo chkstk.obj /dll /out:build\vrayforfabric-Windows-x86_64.dll /implib:build\vrayforfabric-Windows-x86_64.lib /LIBPATH:D:_RESEARCH\vrayappsdk\appsdk-win-nightly-1.07.00-vray33501-20160304\lib /LIBPATH:D:_RESEARCH\vrayappsdk\appsdk-win-nightly-1.07.00-vray33501-20160304\bin vray.lib VRaySDKLibrary.lib build\ImageRegion_functions.obj build\RenderElement_functions.obj build\RenderElements_functions.obj build\RendererOptions_functions.obj build\VRayError_functions.obj build\VRayImage_functions.obj build\VRayInit_functions.obj build\VRayPluginMeta_functions.obj build\VRayPlugin_functions.obj build\VRayPropertyMeta_functions.obj build\VRayPropertyRuntimeMeta_functions.obj build\VRayRenderer_functions.obj build\VRayValue_functions.obj build\VRayVersion_functions.obj build\extension.obj

**Comment by ngcg** [comment]
Hi Thorsten,

I can't test, because I don't have Fabric, but vray.lib should never be necessary for AppSDK-based projects. You only need to link VRaySDKLibrary.lib and that's only one option (this is the case here it seems). The project can also be set up to load VRaySDKLibrary.dll at runtime, so it would only need vraysdk.hpp to compile.

The project page lists a bunch of variables to be set. You could just run setenv27.bat from the AppSDK location instead of doing this yourself. Running scons after that should work, I hope. Again, I just can't verify on my box.

**Comment by ngcg** [comment]
Apart from that we're also working on removing the need for any environment variables when running an AppSDK-based project. It would instead require passing at least one path (to VRaySDKLibrary) from the project's source code, though.

**Comment by instinct-vfx** [comment]
Well i did not add vray.lib, it was part of the sconscript so i assumed it would be needed. I just removed it from the Sconscript file and indeed it seems it is not needed anyways. I am still left with the unresolved external symbols and i am very unsure why that would be the case as the VRaySDKLibrary file is in place.

**Comment by ngcg** [comment]
Looking at your link command, can this be the problem:
 /LIBPATH:D:_RESEARCH\vrayappsdk\appsdk-win-nightly-1.07.00-vray33501-20160304\lib
D:_RESEARCH - no backslash

**Comment by sjparker** [comment]
Hi Thorsten,

I'm looking at this now. Let me confirm everything works in Windows before
you dig any deeper. Admittedly, this was only tested in Linux. Stay-tuned.

-s

On Wed, Mar 9, 2016 at 12:07 PM, Thorsten Kaufmann <notifications@github.com

**Comment by ngcg** [comment]
Oh, btw, I think the 20160304 build may be a bit broken for C++ (not related to your current linkage trouble). We fixed something in the header this Monday. You could try 20160308 instead.

**Comment by instinct-vfx** [comment]
Will try the other build, thanks!

@sjparker : For windows so far i removed vray from the libs list and i also had to change a path slightly. As it was using the /bin path for the LIBPATH it would not find the lib. Then i have an issue with a VS mismatch that is fixed by compiling release rather than debug which i think may be due to my setup.

Cheers,
Thorsten

**Comment by instinct-vfx** [comment]
Seems to work with the other appsdk build. Thanks @ngcg 

@sjparker : Do you prefer me forking and making pull requests or should i just report here what else i changed?

**Comment by sjparker** [comment]
I wouldn't bother forking for this. I can't remember why I had to link (or
thought I had to) that lib. But it definitely made something work that
wasn't. It was probably some LD_LIBRARY_PATH run-time issue that I
mistakenly thought was a linking issue. So let me verify the Linux side of
things. As Nikola stated, use anything newer than 20160304 of the
vrayappsdk. And I'd highly recommend using Fabric 2.1.x as it has many
Canvas related bug fixes.

Let me look into the bin issue. It sounds like you swapped it for /lib and
statically linked as opposed to using the .dll under /bin.

On Wed, Mar 9, 2016 at 12:55 PM, Thorsten Kaufmann <notifications@github.com

**Comment by instinct-vfx** [comment]
Well SCONS did, not me ;)

Will go for 2.1. Was not sure it was supported due to the 2.0.x tag in the readme.

I switched that in the SConscript in /src/ btw.

Cheers,
Thorsten

**Comment by sjparker** [comment]
I meant you probably changed LIBPATH to point to 'lib' instead of 'bin',
correct? This causes static linkage. The scons script is attempting to
dynamically link but for some reason it's NOT inferring the *.dll suffix
and is actually searching for *.lib, so changing the LIBPATH make it find
*.lib ... but I'm going to fix it so it's dynamically linking as it does on
Linux.

**Comment by sjparker** [comment]
Well, that was not fruitful. So I put a OS-specific workaround in the build script for now. I think I'm having permissions issues on Windows 8.1 with *.dll's coming from downloaded zip archives. So until I can get it sorted, we're basically statically linking VRayAppSDK on Windows and dynamically linking on Linux. I confirmed the two tests as well on both platforms.

**Comment by ngcg** [comment]
There is no static lib for VRaySDKLibrary - it's an import lib.
http://stackoverflow.com/questions/6402586/know-if-lib-is-static-or-import

**Comment by sjparker** [comment]
Fair enough. I was only looking at the extension. :)

**Comment by sjparker** [comment]
fixed.
